tb <- dplyr::select(all_fns_dmt_tb %>%
                      dplyr::filter(file_pfx_chr == "fn_"),fns_chr)  %>%
  dplyr::mutate(new_nm = fns_chr %>% remove_obj_type_from_nm()) %>%
  dplyr::mutate(duplicated_lgl = duplicated(new_nm))
tb <- tb %>% dplyr::mutate(new_nm = dplyr::case_when(duplicated_lgl ~ fns_chr,
                                                     new_nm == "create_accessors" ~ "write_slot_gtr_str_mthds",
                                                     new_nm == "create_accessors_rec" ~ "write_gtr_str_mthds_for_slots",
                                                     new_nm == "create_ready_accessors" ~ "make_alg_to_write_gtr_str_mthds",
                                                     new_nm == "create_ready_helper" ~ "make_helper_fn",
                                                     new_nm == "create_ready_show_mthd" ~ "make_show_mthd_fn",
                                                     new_nm == "delete_files" ~ "write_to_delete_fls_with_ptrn",
                                                     new_nm == "delete_getters_setters" ~ "write_to_delete_gnrc_fn_fls",
                                                     new_nm == "gen_pt_value" ~ "make_alg_to_get_pt_val",
                                                     new_nm == "get_class_files" ~ "get_class_fl_nms",
                                                     new_nm == "get_included_classes_chr_vec" ~ "get_nms_of_clss_to_inc",
                                                     new_nm == "get_parent_ns" ~ "get_parent_cls_ns",
                                                     new_nm == "get_parent_proto_fn" ~ "get_parent_cls_pt_fn",
                                                     new_nm == "get_parent_prototypes" ~ "get_parent_cls_pts",
                                                     new_nm == "get_parent_slot_names" ~ "get_parent_cls_slot_nms",
                                                     new_nm == "get_proto_list" ~ "make_pt_ls",
                                                     new_nm == "make_and_tf_curr_gen" ~ "make_tfd_nms_of_curr_gnrcs",
                                                     new_nm == "make_child_fn" ~ "make_child_cls_fn",
                                                     new_nm == "make_class_mk" ~ "make_class_mk_tb_from_ls",
                                                     new_nm == "make_class_type_mk" ~ "make_class_type_mk_tb",
                                                     new_nm == "make_className" ~ "make_alg_to_gen_ref_to_cls",
                                                     new_nm == "make_current_generics" ~ "get_nms_of_curr_gnrcs",
                                                     new_nm == "make_gen_fn" ~ "make_gnrc_fn",
                                                     new_nm == "make_gen_mthd_pair" ~ "make_gnrc_mthd_pair_ls",
                                                     new_nm == "make_generic" ~ "make_alg_to_set_gnrc",
                                                     new_nm == "make_import_packages" ~ "make_ls_of_pkgs_to_imp",
                                                     new_nm == "make_include_tag" ~ "make_dmt_inc_tag",
                                                     new_nm == "make_meth_fn" ~ "tf_fn_into_chr",
                                                     new_nm == "make_method" ~ "make_alg_to_set_mthd",
                                                     new_nm == "make_new_classes" ~ "write_scripts_to_mk_clss",
                                                     new_nm == "make_ready" ~ "write_scripts_to_mk_r3_clss",
                                                     new_nm == "make_ready_s3_checker" ~ "make_fn_pt_to_check_r3_cls_inhtc",
                                                     new_nm == "make_ready_s3_constructor" ~ "make_fn_pt_to_make_unvld_r3_cls_inst",
                                                     new_nm == "make_ready_s3_prototype" ~ "make_fn_pt_to_make_r3_cls_pt",
                                                     new_nm == "make_ready_s3_valid_instance" ~ "make_fn_pt_to_make_vldd_r3_cls_inst",
                                                     new_nm == "make_ready_s3_validator" ~ "make_fn_pt_to_make_vld_r3_cls_inst",
                                                     new_nm == "make_ready_s4" ~ "write_scripts_to_mk_r4_clss",
                                                     new_nm == "make_s3_components" ~ "make_pt_ls_for_new_r3_cls",
                                                     new_nm == "make_s3_mk" ~ "make_pt_tb_for_new_r3_cls",
                                                     new_nm == "make_s3_mk_tb_row" ~ "make_one_row_pt_tb_for_new_r3_cls",
                                                     new_nm == "make_s4_mk" ~ "make_pt_tb_for_new_r4_cls",
                                                     new_nm == "make_s4_mk_tb_row" ~ "make_one_row_pt_tb_for_new_r4_cls",
                                                     #new_nm == "remove_class_from_cache" ~ "remove_class_from_cache"",
                                                     #new_nm == "replace_NA_in_fn" ~ "replace_NA_in_fn",
                                                     new_nm == "resolve_parent_ns" ~ "transform_parent_ns_ls",
                                                     new_nm == "set_old_classes_extend" ~ "make_alg_to_set_old_clss",
                                                     new_nm == "set_ready_class" ~ "write_to_mk_r4_cls",
                                                     new_nm == "simplify_class_name" ~ "transform_alg_to_ref_cls_nm",
                                                     #new_nm == "transform_class_ns" ~ "NEW",
                                                     new_nm == "transform_new_classes" ~ "transform_pt_ls_for_new_clss",
                                                     new_nm == "validate_ready" ~ "make_alg_to_set_validity_of_r4_cls",
                                                     new_nm == "write_accessors" ~ "write_gtr_str_mthds_for_r4",
                                                     new_nm == "write_fn_txt_and_tags" ~ "make_lines_for_writing_dmtd_fn",
                                                     new_nm == "write_gen_meth" ~ "write_scripts_to_make_gnrc_and_mthd",
                                                     new_nm == "write_generic" ~ "write_script_to_make_gnrc",
                                                     new_nm == "write_method" ~ "write_script_to_make_mthd",
                                                     new_nm == "write_s3" ~ "write_mthds_for_r3_or_r4_clss",
                                                     new_nm == "write_std_method" ~ "write_std_mthd",
                                                     TRUE ~ new_nm))
tb <- tb %>% dplyr::mutate(duplicated_lgl = duplicated(new_nm))
any(tb$duplicated_lgl)
replace_fn_nms(tb)
